<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20180927010520 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE t_accompagnemement CHANGE lg_ACCOMPAGNEMENT_ID lg_ACCOMPAGNEMENT_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_alert_event CHANGE str_Event str_Event VARCHAR(40) NOT NULL, CHANGE b_IsCommand b_IsCommand TINYINT(1) DEFAULT NULL, CHANGE b_Row_Active b_Row_Active TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_alert_event_user_fone CHANGE lg_ID lg_ID VARCHAR(20) NOT NULL, CHANGE lg_USER_FONE_ID lg_USER_FONE_ID VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_batiment CHANGE lg_BATIMENT_ID lg_BATIMENT_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_caisse CHANGE lg_CAISSE_ID lg_CAISSE_ID VARCHAR(40) NOT NULL, CHANGE lg_USER_ID lg_USER_ID VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_cash_transaction CHANGE ID ID VARCHAR(40) NOT NULL, CHANGE int_AMOUNT_DEBIT int_AMOUNT_DEBIT INT DEFAULT NULL, CHANGE int_AMOUNT_CREDIT int_AMOUNT_CREDIT INT DEFAULT NULL, CHANGE str_NUMERO_COMPTE str_NUMERO_COMPTE VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_chambre CHANGE lg_CHAMBRE_ID lg_CHAMBRE_ID VARCHAR(30) NOT NULL, CHANGE lg_SERVICES_ID lg_SERVICES_ID VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_channel CHANGE lg_CHANNEL_ID lg_CHANNEL_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_ci_carte CHANGE lg_CI_CARTE_ID lg_CI_CARTE_ID VARCHAR(50) NOT NULL, CHANGE b_IS_SUGGEST b_IS_SUGGEST TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_ci_plat CHANGE lg_CI_PLAT_ID lg_CI_PLAT_ID VARCHAR(50) NOT NULL, CHANGE b_IS_SUGGEST b_IS_SUGGEST TINYINT(1) DEFAULT NULL, CHANGE lg_CI_TYPE_CARTE_ID lg_CI_TYPE_CARTE_ID VARCHAR(50) DEFAULT NULL, CHANGE int_PRIX int_PRIX INT DEFAULT NULL');
        $this->addSql('ALTER TABLE t_ci_type_carte CHANGE lg_CI_TYPE_CARTE_ID lg_CI_TYPE_CARTE_ID VARCHAR(50) NOT NULL, CHANGE lg_CI_CARTE_ID lg_CI_CARTE_ID VARCHAR(50) DEFAULT NULL, CHANGE b_IS_SUGGEST b_IS_SUGGEST TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_coffre_caisse CHANGE ID_COFFRE_CAISSE ID_COFFRE_CAISSE VARCHAR(40) NOT NULL, CHANGE lg_USER_ID lg_USER_ID VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_commentaire CHANGE lg_COMMENTAIRE_ID lg_COMMENTAIRE_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_cs_claviers CHANGE lg_CS_CLAVIERS_ID lg_CS_CLAVIERS_ID VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE t_cs_fenetres CHANGE lg_CS_FENETRES_ID lg_CS_FENETRES_ID VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE t_cs_sous_fenetres CHANGE lg_CS_SOUS_FENETRES_ID lg_CS_SOUS_FENETRES_ID VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE t_customer CHANGE lg_CUSTOMER_ID lg_CUSTOMER_ID VARCHAR(30) NOT NULL, CHANGE str_AUTH_METHODE str_AUTH_METHODE VARCHAR(40) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_customer_account CHANGE lg_CUSTOMER_ACCOUNT_ID lg_CUSTOMER_ACCOUNT_ID VARCHAR(30) NOT NULL, CHANGE lg_CUSTOMER_ID lg_CUSTOMER_ID VARCHAR(30) DEFAULT NULL, CHANGE int_SOLDE int_SOLDE INT DEFAULT NULL');
        $this->addSql('ALTER TABLE t_customer_institutions CHANGE lg_CUSTOMER_INSTITUTIONS_ID lg_CUSTOMER_INSTITUTIONS_ID VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE t_decoupe CHANGE lg_DECOUPE_ID lg_DECOUPE_ID VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE t_depenses CHANGE ID_DEPENSE ID_DEPENSE VARCHAR(40) NOT NULL');
        $this->addSql('ALTER TABLE t_entity_map CHANGE lg_ENTITY_MAP_ID lg_ENTITY_MAP_ID VARCHAR(40) NOT NULL, CHANGE int_INDEX int_INDEX INT DEFAULT NULL, CHANGE str_TYPEBLOCK str_TYPEBLOCK VARCHAR(20) DEFAULT NULL, CHANGE str_STROKE_WIDTH str_STROKE_WIDTH VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_etage CHANGE lg_ETAGE_ID lg_ETAGE_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_event_log CHANGE lg_EVENT_LOG_ID lg_EVENT_LOG_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_famille CHANGE lg_FAMILLE_ID lg_FAMILLE_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_file_data_patient CHANGE lg_ID lg_ID VARCHAR(40) NOT NULL');
        $this->addSql('ALTER TABLE t_imprimante CHANGE lg_IMPRIMANTE_ID lg_IMPRIMANTE_ID VARCHAR(40) NOT NULL');
        $this->addSql('ALTER TABLE t_inboud_message CHANGE lg_INBOUND_MESSAGE_ID lg_INBOUND_MESSAGE_ID VARCHAR(30) NOT NULL');
        $this->addSql('DROP INDEX lg_INSTITUTION_ID ON t_institutions');
        $this->addSql('ALTER TABLE t_institutions CHANGE lg_INSTITUTION_ID lg_INSTITUTION_ID VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE t_jour_semaine CHANGE lg_JOUR_SEMAINE_ID lg_JOUR_SEMAINE_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_language CHANGE lg_Language_ID lg_Language_ID VARCHAR(20) NOT NULL, CHANGE str_Local_Cty str_Local_Cty VARCHAR(20) DEFAULT NULL, CHANGE str_Local_Lg str_Local_Lg VARCHAR(20) DEFAULT NULL, CHANGE str_Code str_Code VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_lit CHANGE lg_LIT_ID lg_LIT_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_lit_occupation CHANGE lg_LIT_OCCUPATION_ID lg_LIT_OCCUPATION_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_lit_occupation_statut CHANGE lg_LIT_OCCUPATION_STATUT_ID lg_LIT_OCCUPATION_STATUT_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_menu CHANGE lg_MENU_ID lg_MENU_ID VARCHAR(20) NOT NULL, CHANGE int_PRIORITY int_PRIORITY INT DEFAULT NULL');
        $this->addSql('ALTER TABLE t_menu_repas CHANGE lg_MENU_REPAS_ID lg_MENU_REPAS_ID VARCHAR(30) NOT NULL, CHANGE int_AMOUNT int_AMOUNT INT DEFAULT NULL');
        $this->addSql('ALTER TABLE t_menu_repas_product_item CHANGE lg_MENU_REPAS_PRODUCT_ITEM_ID lg_MENU_REPAS_PRODUCT_ITEM_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_message CHANGE lg_MESSAGE_ID lg_MESSAGE_ID VARCHAR(50) NOT NULL, CHANGE str_STATUT str_STATUT VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_mode_reglement CHANGE lg_MODE_REGLEMENT_ID lg_MODE_REGLEMENT_ID VARCHAR(40) NOT NULL');
        $this->addSql('ALTER TABLE t_module CHANGE lg_MODULE_ID lg_MODULE_ID VARCHAR(20) NOT NULL, CHANGE int_PRIORITY int_PRIORITY INT DEFAULT NULL');
        $this->addSql('ALTER TABLE t_mouvement CHANGE lg_MOUVEMENT_ID lg_MOUVEMENT_ID VARCHAR(40) NOT NULL, CHANGE lg_FAMILLE_ID lg_FAMILLE_ID VARCHAR(30) DEFAULT NULL, CHANGE lg_USER_ID lg_USER_ID VARCHAR(30) DEFAULT NULL, CHANGE int_NUMBER int_NUMBER INT DEFAULT NULL, CHANGE int_STOCK_JOUR int_STOCK_JOUR INT DEFAULT NULL, CHANGE int_NUMBERTRANSACTION int_NUMBERTRANSACTION INT DEFAULT NULL');
        $this->addSql('ALTER TABLE t_mouvementprice CHANGE lg_MOUVEMENTPRICE_ID lg_MOUVEMENTPRICE_ID VARCHAR(40) NOT NULL, CHANGE lg_FAMILLE_ID lg_FAMILLE_ID VARCHAR(30) DEFAULT NULL, CHANGE lg_USER_ID lg_USER_ID VARCHAR(30) DEFAULT NULL, CHANGE int_PRICE_OLD int_PRICE_OLD INT DEFAULT NULL, CHANGE int_PRICE_NEW int_PRICE_NEW INT DEFAULT NULL, CHANGE int_ECART int_ECART INT DEFAULT NULL');
        $this->addSql('ALTER TABLE t_mouvement_snapshot CHANGE lg_MOUVEMENT_SNAPSHOT_ID lg_MOUVEMENT_SNAPSHOT_ID VARCHAR(40) NOT NULL, CHANGE lg_FAMILLE_ID lg_FAMILLE_ID VARCHAR(30) DEFAULT NULL, CHANGE int_STOCK_JOUR int_STOCK_JOUR INT DEFAULT NULL, CHANGE int_NUMBERTRANSACTION int_NUMBERTRANSACTION INT DEFAULT NULL');
        $this->addSql('ALTER TABLE t_mvt_caisse CHANGE lg_MVT_CAISSE_ID lg_MVT_CAISSE_ID VARCHAR(40) NOT NULL, CHANGE lg_TYPE_MVT_CAISSE_ID lg_TYPE_MVT_CAISSE_ID VARCHAR(40) DEFAULT NULL, CHANGE str_CREATED_BY str_CREATED_BY VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_notification CHANGE lg_ID lg_ID VARCHAR(40) NOT NULL');
        $this->addSql('ALTER TABLE t_order CHANGE lg_ORDER_ID lg_ORDER_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_order_customer_account CHANGE lg_ORDER_CUSTOMER_ACCOUNT_ID lg_ORDER_CUSTOMER_ACCOUNT_ID VARCHAR(30) NOT NULL, CHANGE lg_CUSTOMER_ACCOUNT_ID lg_CUSTOMER_ACCOUNT_ID VARCHAR(30) DEFAULT NULL, CHANGE lg_ORDER_ID lg_ORDER_ID VARCHAR(30) DEFAULT NULL, CHANGE lg_PARENT_ID lg_PARENT_ID VARCHAR(30) DEFAULT NULL, CHANGE lg_LIT_OCCUPATION_ID lg_LIT_OCCUPATION_ID VARCHAR(30) DEFAULT NULL, CHANGE lg_MENU_REPAS_ID lg_MENU_REPAS_ID VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_order_transaction CHANGE lg_ORDER_TRANSACTION_ID lg_ORDER_TRANSACTION_ID VARCHAR(30) NOT NULL, CHANGE lg_ACCOMPAGNEMENT_ID lg_ACCOMPAGNEMENT_ID VARCHAR(30) DEFAULT NULL, CHANGE lg_COMMENTAIRE_ID lg_COMMENTAIRE_ID VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_order_transaction_commentaire CHANGE lg_ID lg_ID VARCHAR(40) NOT NULL, CHANGE lg_ORDER_TRANSACTION_ID lg_ORDER_TRANSACTION_ID VARCHAR(30) DEFAULT NULL, CHANGE lg_COMMENTAIRE_ID lg_COMMENTAIRE_ID VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_outboud_message CHANGE lg_OUTBOUND_MESSAGE_ID lg_OUTBOUND_MESSAGE_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_parameters CHANGE str_KEY str_KEY VARCHAR(50) NOT NULL, CHANGE str_STATUT str_STATUT VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_preference_schema_carte CHANGE lg_PREFERENCE_SCHEMA_CARTE_ID lg_PREFERENCE_SCHEMA_CARTE_ID VARCHAR(40) NOT NULL, CHANGE lg_CUSTOMER_ID lg_CUSTOMER_ID VARCHAR(30) DEFAULT NULL, CHANGE lg_SCHEMA_CARTE_ID lg_SCHEMA_CARTE_ID VARCHAR(20) DEFAULT NULL, CHANGE lg_REPORT_ID lg_REPORT_ID VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_privilege CHANGE lg_PRIVELEGE_ID lg_PRIVELEGE_ID VARCHAR(50) NOT NULL, CHANGE str_STATUT str_STATUT VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_product_iem_type_contenance CHANGE lg_PRODUCT_ITEM_TYPE_CONTENANCE_ID lg_PRODUCT_ITEM_TYPE_CONTENANCE_ID VARCHAR(40) NOT NULL, CHANGE lg_TYPE_CONTENANCE_ID lg_TYPE_CONTENANCE_ID VARCHAR(40) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_product_item CHANGE lg_PRODUCT_ITEM_ID lg_PRODUCT_ITEM_ID VARCHAR(30) NOT NULL, CHANGE int_STOCK_MINIMAL int_STOCK_MINIMAL INT DEFAULT NULL, CHANGE b_IS_COMMENTAIRE b_IS_COMMENTAIRE TINYINT(1) DEFAULT NULL, CHANGE b_IS_COMPILATION b_IS_COMPILATION TINYINT(1) DEFAULT NULL, CHANGE b_IS_FOR_SALE b_IS_FOR_SALE TINYINT(1) DEFAULT NULL, CHANGE b_IS_REMISED b_IS_REMISED TINYINT(1) DEFAULT NULL, CHANGE lg_FAMILLE_ID lg_FAMILLE_ID VARCHAR(30) DEFAULT NULL, CHANGE int_PRIX_ACHAT int_PRIX_ACHAT INT DEFAULT NULL');
        $this->addSql('ALTER TABLE t_product_item_accompagnemement CHANGE lg_PRODUCT_ITEM_ACCOMPAGNEMENT_ID lg_PRODUCT_ITEM_ACCOMPAGNEMENT_ID VARCHAR(30) NOT NULL, CHANGE lg_ACCOMPAGNEMENT_ID lg_ACCOMPAGNEMENT_ID VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_product_item_commentaire CHANGE lg_PRODUCT_ITEM_ACCOMPAGNEMENT_ID lg_PRODUCT_ITEM_ACCOMPAGNEMENT_ID VARCHAR(30) NOT NULL, CHANGE lg_COMMENTAIRE_ID lg_COMMENTAIRE_ID VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_product_item_stock CHANGE lg_PRODUCT_ITEM_STOCK_ID lg_PRODUCT_ITEM_STOCK_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_product_item_type_contenance_stock CHANGE lg_PRODUCT_ITEM_TYPE_CONTENANCE_STOCK_ID lg_PRODUCT_ITEM_TYPE_CONTENANCE_STOCK_ID VARCHAR(40) NOT NULL');
        $this->addSql('ALTER TABLE t_quest_qcm CHANGE lg_QUEST_QCM_ID lg_QUEST_QCM_ID VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE t_recettes CHANGE ID_RECETTE ID_RECETTE VARCHAR(40) NOT NULL');
        $this->addSql('ALTER TABLE t_reponse_qcm CHANGE lg_REPONSE_QCM_ID lg_REPONSE_QCM_ID VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE t_report CHANGE lg_REPORT_ID lg_REPORT_ID VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE t_report_groupe CHANGE lg_REPORT_GROUPE_ID lg_REPORT_GROUPE_ID VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE t_resume_caisse CHANGE ld_CAISSE_ID ld_CAISSE_ID VARCHAR(40) NOT NULL, CHANGE lg_USER_ID lg_USER_ID VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_role CHANGE lg_ROLE_ID lg_ROLE_ID VARCHAR(20) NOT NULL, CHANGE str_TYPE str_TYPE VARCHAR(20) DEFAULT NULL, CHANGE str_STATUT str_STATUT VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_role_privelege CHANGE lg_ROLE_PRIVILEGE lg_ROLE_PRIVILEGE VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_role_user CHANGE lg_USER_ROLE_ID lg_USER_ROLE_ID VARCHAR(30) NOT NULL, CHANGE lg_ROLE_ID lg_ROLE_ID VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_satisfaction CHANGE lg_SATISFACTION_ID lg_SATISFACTION_ID VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE t_schema_carte CHANGE lg_SCHEMA_CARTE_ID lg_SCHEMA_CARTE_ID VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE t_services CHANGE lg_SERVICES_ID lg_SERVICES_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_skin CHANGE lg_SKIN_ID lg_SKIN_ID VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE t_sms CHANGE ID_SMS ID_SMS VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE t_sms_customer CHANGE ID ID VARCHAR(40) NOT NULL, CHANGE lg_CUSTOMER_ID lg_CUSTOMER_ID VARCHAR(30) DEFAULT NULL, CHANGE ID_SMS ID_SMS VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_sms_not_send CHANGE ID_SMS ID_SMS VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE t_snap_shop_daly_recette CHANGE lg_ID lg_ID VARCHAR(50) NOT NULL, CHANGE lg_TYPE_RECETTE_ID lg_TYPE_RECETTE_ID VARCHAR(40) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_sous_menu CHANGE lg_SOUS_MENU_ID lg_SOUS_MENU_ID VARCHAR(20) NOT NULL, CHANGE int_PRIORITY int_PRIORITY INT DEFAULT NULL');
        $this->addSql('ALTER TABLE t_table CHANGE lg_TABLE_ID lg_TABLE_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_tournee_livraison CHANGE lg_TOURNEE_LIVRAISON_ID lg_TOURNEE_LIVRAISON_ID VARCHAR(30) NOT NULL, CHANGE lg_USER_ID lg_USER_ID VARCHAR(30) DEFAULT NULL, CHANGE int_TOTAL int_TOTAL INT DEFAULT NULL, CHANGE int_TO_DO int_TO_DO INT DEFAULT NULL');
        $this->addSql('ALTER TABLE t_tournee_livraison_order CHANGE lg_TOURNEE_LIVRAISON_ORDER_ID lg_TOURNEE_LIVRAISON_ORDER_ID VARCHAR(30) NOT NULL, CHANGE lg_TOURNEE_LIVRAISON_ID lg_TOURNEE_LIVRAISON_ID VARCHAR(30) DEFAULT NULL, CHANGE lg_ORDER_ID lg_ORDER_ID VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_type_contenance CHANGE lg_TYPE_CONTENANCE_ID lg_TYPE_CONTENANCE_ID VARCHAR(40) NOT NULL');
        $this->addSql('ALTER TABLE t_type_depense CHANGE lg_TYPE_DEPENSE_ID lg_TYPE_DEPENSE_ID VARCHAR(40) NOT NULL');
        $this->addSql('ALTER TABLE t_type_ecart_mvt CHANGE lg_TYPE_ECART_MVT lg_TYPE_ECART_MVT VARCHAR(40) NOT NULL');
        $this->addSql('ALTER TABLE t_type_mvt_caisse CHANGE lg_TYPE_MVT_CAISSE_ID lg_TYPE_MVT_CAISSE_ID VARCHAR(40) NOT NULL');
        $this->addSql('ALTER TABLE t_type_quest_qcm CHANGE lg_TYPE_QUEST_QCM_ID lg_TYPE_QUEST_QCM_ID VARCHAR(20) NOT NULL, CHANGE lg_QUEST_QCM_ID lg_QUEST_QCM_ID VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_type_recette CHANGE lg_TYPE_RECETTE_ID lg_TYPE_RECETTE_ID VARCHAR(40) NOT NULL, CHANGE is_USE_TVA is_USE_TVA TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_type_reglement CHANGE lg_TYPE_REGLEMENT_ID lg_TYPE_REGLEMENT_ID VARCHAR(40) NOT NULL');
        $this->addSql('ALTER TABLE t_type_vente CHANGE lg_TYPE_VENTE_ID lg_TYPE_VENTE_ID VARCHAR(40) NOT NULL');
        $this->addSql('ALTER TABLE t_user ADD username VARCHAR(25) NOT NULL, ADD password VARCHAR(64) NOT NULL, ADD email VARCHAR(254) NOT NULL, ADD is_active TINYINT(1) NOT NULL, CHANGE lg_USER_ID lg_USER_ID VARCHAR(30) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_37E5BF3BF85E0677 ON t_user (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_37E5BF3BE7927C74 ON t_user (email)');
        $this->addSql('ALTER TABLE t_user_fone CHANGE lg_USER_FONE_ID lg_USER_FONE_ID VARCHAR(30) NOT NULL, CHANGE lg_USER_ID lg_USER_ID VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_user_imprimante CHANGE lg_USER_IMPRIMQNTE_ID lg_USER_IMPRIMQNTE_ID VARCHAR(40) NOT NULL, CHANGE lg_USER_ID lg_USER_ID VARCHAR(30) DEFAULT NULL, CHANGE lg_IMPRIMANTE_ID lg_IMPRIMANTE_ID VARCHAR(40) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_user_services CHANGE lg_USER_SERVICES_ID lg_USER_SERVICES_ID VARCHAR(30) NOT NULL, CHANGE lg_USER_ID lg_USER_ID VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_warehouse CHANGE lg_WAREHOUSE_ID lg_WAREHOUSE_ID VARCHAR(40) NOT NULL');
        $this->addSql('ALTER TABLE t_warehouse_contenance CHANGE lg_WAREHOUSE_CONTENANCE_ID lg_WAREHOUSE_CONTENANCE_ID VARCHAR(40) NOT NULL, CHANGE lg_PRODUCT_ITEM_TYPE_CONTENANCE_ID lg_PRODUCT_ITEM_TYPE_CONTENANCE_ID VARCHAR(40) DEFAULT NULL');
        $this->addSql('ALTER TABLE t_zonne_1 CHANGE lg_ZONNE_1_ID lg_ZONNE_1_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_zonne_2 CHANGE lg_ZONNE_2_ID lg_ZONNE_2_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_zonne_3 CHANGE lg_ZONNE_3_ID lg_ZONNE_3_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_zonne_4 CHANGE lg_ZONNE_4_ID lg_ZONNE_4_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_zonne_5 CHANGE lg_ZONNE_5_ID lg_ZONNE_5_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_zonne_6 CHANGE lg_ZONNE_6_ID lg_ZONNE_6_ID VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE t_zonne_7 CHANGE lg_ZONNE_7_ID lg_ZONNE_7_ID VARCHAR(30) NOT NULL');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE t_accompagnemement CHANGE lg_ACCOMPAGNEMENT_ID lg_ACCOMPAGNEMENT_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_alert_event CHANGE str_Event str_Event VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci, CHANGE b_IsCommand b_IsCommand TINYINT(1) DEFAULT \'0\', CHANGE b_Row_Active b_Row_Active TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE t_alert_event_user_fone CHANGE lg_ID lg_ID VARCHAR(20) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_USER_FONE_ID lg_USER_FONE_ID VARCHAR(20) DEFAULT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_batiment CHANGE lg_BATIMENT_ID lg_BATIMENT_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_caisse CHANGE lg_CAISSE_ID lg_CAISSE_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_USER_ID lg_USER_ID VARCHAR(40) DEFAULT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_cash_transaction CHANGE ID ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci, CHANGE int_AMOUNT_DEBIT int_AMOUNT_DEBIT INT DEFAULT 0, CHANGE int_AMOUNT_CREDIT int_AMOUNT_CREDIT INT DEFAULT 0, CHANGE str_NUMERO_COMPTE str_NUMERO_COMPTE VARCHAR(20) DEFAULT \'0000001\' COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_chambre CHANGE lg_CHAMBRE_ID lg_CHAMBRE_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_SERVICES_ID lg_SERVICES_ID VARCHAR(20) DEFAULT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_channel CHANGE lg_CHANNEL_ID lg_CHANNEL_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_ci_carte CHANGE lg_CI_CARTE_ID lg_CI_CARTE_ID VARCHAR(50) NOT NULL COLLATE latin1_swedish_ci, CHANGE b_IS_SUGGEST b_IS_SUGGEST TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE t_ci_plat CHANGE lg_CI_PLAT_ID lg_CI_PLAT_ID VARCHAR(50) NOT NULL COLLATE latin1_swedish_ci, CHANGE b_IS_SUGGEST b_IS_SUGGEST TINYINT(1) DEFAULT \'0\', CHANGE int_PRIX int_PRIX INT DEFAULT 0, CHANGE lg_CI_TYPE_CARTE_ID lg_CI_TYPE_CARTE_ID VARCHAR(50) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_ci_type_carte CHANGE lg_CI_TYPE_CARTE_ID lg_CI_TYPE_CARTE_ID VARCHAR(50) NOT NULL COLLATE latin1_swedish_ci, CHANGE b_IS_SUGGEST b_IS_SUGGEST TINYINT(1) DEFAULT \'0\', CHANGE lg_CI_CARTE_ID lg_CI_CARTE_ID VARCHAR(50) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_coffre_caisse CHANGE ID_COFFRE_CAISSE ID_COFFRE_CAISSE VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_USER_ID lg_USER_ID VARCHAR(40) DEFAULT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_commentaire CHANGE lg_COMMENTAIRE_ID lg_COMMENTAIRE_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_cs_claviers CHANGE lg_CS_CLAVIERS_ID lg_CS_CLAVIERS_ID VARCHAR(20) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_cs_fenetres CHANGE lg_CS_FENETRES_ID lg_CS_FENETRES_ID VARCHAR(20) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_cs_sous_fenetres CHANGE lg_CS_SOUS_FENETRES_ID lg_CS_SOUS_FENETRES_ID VARCHAR(20) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_customer CHANGE lg_CUSTOMER_ID lg_CUSTOMER_ID VARCHAR(30) DEFAULT \'\' NOT NULL COLLATE latin1_swedish_ci, CHANGE str_AUTH_METHODE str_AUTH_METHODE VARCHAR(40) DEFAULT \'FLEX_COMPTA\' COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_customer_account CHANGE lg_CUSTOMER_ACCOUNT_ID lg_CUSTOMER_ACCOUNT_ID VARCHAR(30) DEFAULT \'\' NOT NULL COLLATE latin1_swedish_ci, CHANGE int_SOLDE int_SOLDE INT DEFAULT 0, CHANGE lg_CUSTOMER_ID lg_CUSTOMER_ID VARCHAR(30) DEFAULT \'\' NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_customer_institutions CHANGE lg_CUSTOMER_INSTITUTIONS_ID lg_CUSTOMER_INSTITUTIONS_ID VARCHAR(50) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_decoupe CHANGE lg_DECOUPE_ID lg_DECOUPE_ID VARCHAR(20) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_depenses CHANGE ID_DEPENSE ID_DEPENSE VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_entity_map CHANGE lg_ENTITY_MAP_ID lg_ENTITY_MAP_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci, CHANGE int_INDEX int_INDEX INT DEFAULT 20, CHANGE str_TYPEBLOCK str_TYPEBLOCK VARCHAR(20) DEFAULT \'SIMPLE\' COLLATE latin1_swedish_ci, CHANGE str_STROKE_WIDTH str_STROKE_WIDTH VARCHAR(20) DEFAULT \'1\' COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_etage CHANGE lg_ETAGE_ID lg_ETAGE_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_event_log CHANGE lg_EVENT_LOG_ID lg_EVENT_LOG_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_famille CHANGE lg_FAMILLE_ID lg_FAMILLE_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_file_data_patient CHANGE lg_ID lg_ID VARCHAR(40) NOT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE t_imprimante CHANGE lg_IMPRIMANTE_ID lg_IMPRIMANTE_ID VARCHAR(40) NOT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE t_inboud_message CHANGE lg_INBOUND_MESSAGE_ID lg_INBOUND_MESSAGE_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_institutions CHANGE lg_INSTITUTION_ID lg_INSTITUTION_ID VARCHAR(50) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('CREATE UNIQUE INDEX lg_INSTITUTION_ID ON t_institutions (lg_INSTITUTION_ID)');
        $this->addSql('ALTER TABLE t_jour_semaine CHANGE lg_JOUR_SEMAINE_ID lg_JOUR_SEMAINE_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_language CHANGE lg_Language_ID lg_Language_ID VARCHAR(20) NOT NULL COLLATE latin1_swedish_ci, CHANGE str_Local_Cty str_Local_Cty VARCHAR(20) DEFAULT \'fr\' COLLATE latin1_swedish_ci, CHANGE str_Local_Lg str_Local_Lg VARCHAR(20) DEFAULT \'FR\' COLLATE latin1_swedish_ci, CHANGE str_Code str_Code VARCHAR(50) DEFAULT \'ml_French\' COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_lit CHANGE lg_LIT_ID lg_LIT_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_lit_occupation CHANGE lg_LIT_OCCUPATION_ID lg_LIT_OCCUPATION_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_lit_occupation_statut CHANGE lg_LIT_OCCUPATION_STATUT_ID lg_LIT_OCCUPATION_STATUT_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_menu CHANGE lg_MENU_ID lg_MENU_ID VARCHAR(20) NOT NULL COLLATE latin1_swedish_ci, CHANGE int_PRIORITY int_PRIORITY INT DEFAULT 0');
        $this->addSql('ALTER TABLE t_menu_repas CHANGE lg_MENU_REPAS_ID lg_MENU_REPAS_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci, CHANGE int_AMOUNT int_AMOUNT INT DEFAULT 0');
        $this->addSql('ALTER TABLE t_menu_repas_product_item CHANGE lg_MENU_REPAS_PRODUCT_ITEM_ID lg_MENU_REPAS_PRODUCT_ITEM_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_message CHANGE lg_MESSAGE_ID lg_MESSAGE_ID VARCHAR(50) NOT NULL COLLATE latin1_swedish_ci, CHANGE str_STATUT str_STATUT VARCHAR(20) DEFAULT \'enable\' COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_mode_reglement CHANGE lg_MODE_REGLEMENT_ID lg_MODE_REGLEMENT_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_module CHANGE lg_MODULE_ID lg_MODULE_ID VARCHAR(20) NOT NULL COLLATE latin1_swedish_ci, CHANGE int_PRIORITY int_PRIORITY INT DEFAULT 0');
        $this->addSql('ALTER TABLE t_mouvement CHANGE lg_MOUVEMENT_ID lg_MOUVEMENT_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci, CHANGE int_NUMBER int_NUMBER INT DEFAULT 0, CHANGE int_STOCK_JOUR int_STOCK_JOUR INT DEFAULT 0, CHANGE int_NUMBERTRANSACTION int_NUMBERTRANSACTION INT DEFAULT 0, CHANGE lg_FAMILLE_ID lg_FAMILLE_ID VARCHAR(50) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_USER_ID lg_USER_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_mouvement_snapshot CHANGE lg_MOUVEMENT_SNAPSHOT_ID lg_MOUVEMENT_SNAPSHOT_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci, CHANGE int_STOCK_JOUR int_STOCK_JOUR INT DEFAULT 0, CHANGE int_NUMBERTRANSACTION int_NUMBERTRANSACTION INT DEFAULT 0, CHANGE lg_FAMILLE_ID lg_FAMILLE_ID VARCHAR(50) DEFAULT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_mouvementprice CHANGE lg_MOUVEMENTPRICE_ID lg_MOUVEMENTPRICE_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci, CHANGE int_PRICE_OLD int_PRICE_OLD INT DEFAULT 0, CHANGE int_PRICE_NEW int_PRICE_NEW INT DEFAULT 0, CHANGE int_ECART int_ECART INT DEFAULT 0, CHANGE lg_FAMILLE_ID lg_FAMILLE_ID VARCHAR(50) DEFAULT NULL COLLATE latin1_swedish_ci, CHANGE lg_USER_ID lg_USER_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_mvt_caisse CHANGE lg_MVT_CAISSE_ID lg_MVT_CAISSE_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_TYPE_MVT_CAISSE_ID lg_TYPE_MVT_CAISSE_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci, CHANGE str_CREATED_BY str_CREATED_BY VARCHAR(40) DEFAULT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_notification CHANGE lg_ID lg_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_order CHANGE lg_ORDER_ID lg_ORDER_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_order_customer_account CHANGE lg_ORDER_CUSTOMER_ACCOUNT_ID lg_ORDER_CUSTOMER_ACCOUNT_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_PARENT_ID lg_PARENT_ID VARCHAR(30) DEFAULT \'\' COLLATE latin1_swedish_ci, CHANGE lg_LIT_OCCUPATION_ID lg_LIT_OCCUPATION_ID VARCHAR(40) DEFAULT NULL COLLATE latin1_swedish_ci, CHANGE lg_MENU_REPAS_ID lg_MENU_REPAS_ID VARCHAR(40) DEFAULT NULL COLLATE latin1_swedish_ci, CHANGE lg_CUSTOMER_ACCOUNT_ID lg_CUSTOMER_ACCOUNT_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_ORDER_ID lg_ORDER_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_order_transaction CHANGE lg_ORDER_TRANSACTION_ID lg_ORDER_TRANSACTION_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_ACCOMPAGNEMENT_ID lg_ACCOMPAGNEMENT_ID VARCHAR(40) DEFAULT NULL COLLATE latin1_swedish_ci, CHANGE lg_COMMENTAIRE_ID lg_COMMENTAIRE_ID VARCHAR(20) DEFAULT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_order_transaction_commentaire CHANGE lg_ID lg_ID VARCHAR(40) NOT NULL COLLATE utf8_general_ci, CHANGE lg_COMMENTAIRE_ID lg_COMMENTAIRE_ID VARCHAR(40) DEFAULT NULL COLLATE latin1_swedish_ci, CHANGE lg_ORDER_TRANSACTION_ID lg_ORDER_TRANSACTION_ID VARCHAR(40) DEFAULT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_outboud_message CHANGE lg_OUTBOUND_MESSAGE_ID lg_OUTBOUND_MESSAGE_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_parameters CHANGE str_KEY str_KEY VARCHAR(50) NOT NULL COLLATE latin1_swedish_ci, CHANGE str_STATUT str_STATUT VARCHAR(20) DEFAULT \'enable\' COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_preference_schema_carte CHANGE lg_PREFERENCE_SCHEMA_CARTE_ID lg_PREFERENCE_SCHEMA_CARTE_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_CUSTOMER_ID lg_CUSTOMER_ID VARCHAR(40) DEFAULT NULL COLLATE latin1_swedish_ci, CHANGE lg_SCHEMA_CARTE_ID lg_SCHEMA_CARTE_ID VARCHAR(40) DEFAULT NULL COLLATE latin1_swedish_ci, CHANGE lg_REPORT_ID lg_REPORT_ID VARCHAR(40) DEFAULT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_privilege CHANGE lg_PRIVELEGE_ID lg_PRIVELEGE_ID VARCHAR(50) NOT NULL COLLATE latin1_swedish_ci, CHANGE str_STATUT str_STATUT VARCHAR(50) DEFAULT \'enable\' COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_product_iem_type_contenance CHANGE lg_PRODUCT_ITEM_TYPE_CONTENANCE_ID lg_PRODUCT_ITEM_TYPE_CONTENANCE_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_TYPE_CONTENANCE_ID lg_TYPE_CONTENANCE_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_product_item CHANGE lg_PRODUCT_ITEM_ID lg_PRODUCT_ITEM_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci, CHANGE int_STOCK_MINIMAL int_STOCK_MINIMAL INT DEFAULT 0, CHANGE b_IS_COMMENTAIRE b_IS_COMMENTAIRE TINYINT(1) DEFAULT \'0\', CHANGE b_IS_COMPILATION b_IS_COMPILATION TINYINT(1) DEFAULT \'0\', CHANGE b_IS_FOR_SALE b_IS_FOR_SALE TINYINT(1) DEFAULT \'0\', CHANGE b_IS_REMISED b_IS_REMISED TINYINT(1) DEFAULT \'0\', CHANGE int_PRIX_ACHAT int_PRIX_ACHAT INT DEFAULT 0, CHANGE lg_FAMILLE_ID lg_FAMILLE_ID VARCHAR(40) DEFAULT \'1\' NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_product_item_accompagnemement CHANGE lg_PRODUCT_ITEM_ACCOMPAGNEMENT_ID lg_PRODUCT_ITEM_ACCOMPAGNEMENT_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_ACCOMPAGNEMENT_ID lg_ACCOMPAGNEMENT_ID VARCHAR(40) DEFAULT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_product_item_commentaire CHANGE lg_PRODUCT_ITEM_ACCOMPAGNEMENT_ID lg_PRODUCT_ITEM_ACCOMPAGNEMENT_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_COMMENTAIRE_ID lg_COMMENTAIRE_ID VARCHAR(40) DEFAULT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_product_item_stock CHANGE lg_PRODUCT_ITEM_STOCK_ID lg_PRODUCT_ITEM_STOCK_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_product_item_type_contenance_stock CHANGE lg_PRODUCT_ITEM_TYPE_CONTENANCE_STOCK_ID lg_PRODUCT_ITEM_TYPE_CONTENANCE_STOCK_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_quest_qcm CHANGE lg_QUEST_QCM_ID lg_QUEST_QCM_ID VARCHAR(20) NOT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE t_recettes CHANGE ID_RECETTE ID_RECETTE VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_reponse_qcm CHANGE lg_REPONSE_QCM_ID lg_REPONSE_QCM_ID VARCHAR(20) NOT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE t_report CHANGE lg_REPORT_ID lg_REPORT_ID VARCHAR(20) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_report_groupe CHANGE lg_REPORT_GROUPE_ID lg_REPORT_GROUPE_ID VARCHAR(20) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_resume_caisse CHANGE ld_CAISSE_ID ld_CAISSE_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_USER_ID lg_USER_ID VARCHAR(40) DEFAULT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_role CHANGE lg_ROLE_ID lg_ROLE_ID VARCHAR(20) NOT NULL COLLATE latin1_swedish_ci, CHANGE str_TYPE str_TYPE VARCHAR(20) DEFAULT \'custom\' COLLATE latin1_swedish_ci, CHANGE str_STATUT str_STATUT VARCHAR(50) DEFAULT \'enable\' COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_role_privelege CHANGE lg_ROLE_PRIVILEGE lg_ROLE_PRIVILEGE VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_role_user CHANGE lg_USER_ROLE_ID lg_USER_ROLE_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_ROLE_ID lg_ROLE_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_satisfaction CHANGE lg_SATISFACTION_ID lg_SATISFACTION_ID VARCHAR(20) NOT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE t_schema_carte CHANGE lg_SCHEMA_CARTE_ID lg_SCHEMA_CARTE_ID VARCHAR(20) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_services CHANGE lg_SERVICES_ID lg_SERVICES_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_skin CHANGE lg_SKIN_ID lg_SKIN_ID VARCHAR(20) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_sms CHANGE ID_SMS ID_SMS VARCHAR(50) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_sms_customer CHANGE ID ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci, CHANGE ID_SMS ID_SMS VARCHAR(40) DEFAULT NULL COLLATE latin1_swedish_ci, CHANGE lg_CUSTOMER_ID lg_CUSTOMER_ID VARCHAR(40) DEFAULT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_sms_not_send CHANGE ID_SMS ID_SMS VARCHAR(50) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_snap_shop_daly_recette CHANGE lg_ID lg_ID VARCHAR(50) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_TYPE_RECETTE_ID lg_TYPE_RECETTE_ID VARCHAR(50) DEFAULT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_sous_menu CHANGE lg_SOUS_MENU_ID lg_SOUS_MENU_ID VARCHAR(20) DEFAULT \'\' NOT NULL COLLATE latin1_swedish_ci, CHANGE int_PRIORITY int_PRIORITY INT DEFAULT 0');
        $this->addSql('ALTER TABLE t_table CHANGE lg_TABLE_ID lg_TABLE_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_tournee_livraison CHANGE lg_TOURNEE_LIVRAISON_ID lg_TOURNEE_LIVRAISON_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci, CHANGE int_TOTAL int_TOTAL INT DEFAULT 0, CHANGE int_TO_DO int_TO_DO INT DEFAULT 0, CHANGE lg_USER_ID lg_USER_ID VARCHAR(50) DEFAULT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_tournee_livraison_order CHANGE lg_TOURNEE_LIVRAISON_ORDER_ID lg_TOURNEE_LIVRAISON_ORDER_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_TOURNEE_LIVRAISON_ID lg_TOURNEE_LIVRAISON_ID VARCHAR(50) DEFAULT NULL COLLATE latin1_swedish_ci, CHANGE lg_ORDER_ID lg_ORDER_ID VARCHAR(50) DEFAULT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_type_contenance CHANGE lg_TYPE_CONTENANCE_ID lg_TYPE_CONTENANCE_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_type_depense CHANGE lg_TYPE_DEPENSE_ID lg_TYPE_DEPENSE_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_type_ecart_mvt CHANGE lg_TYPE_ECART_MVT lg_TYPE_ECART_MVT VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_type_mvt_caisse CHANGE lg_TYPE_MVT_CAISSE_ID lg_TYPE_MVT_CAISSE_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_type_quest_qcm CHANGE lg_TYPE_QUEST_QCM_ID lg_TYPE_QUEST_QCM_ID VARCHAR(20) NOT NULL COLLATE utf8_general_ci, CHANGE lg_QUEST_QCM_ID lg_QUEST_QCM_ID VARCHAR(20) NOT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE t_type_recette CHANGE lg_TYPE_RECETTE_ID lg_TYPE_RECETTE_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci, CHANGE is_USE_TVA is_USE_TVA TINYINT(1) DEFAULT \'0\'');
        $this->addSql('ALTER TABLE t_type_reglement CHANGE lg_TYPE_REGLEMENT_ID lg_TYPE_REGLEMENT_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_type_vente CHANGE lg_TYPE_VENTE_ID lg_TYPE_VENTE_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('DROP INDEX UNIQ_37E5BF3BF85E0677 ON t_user');
        $this->addSql('DROP INDEX UNIQ_37E5BF3BE7927C74 ON t_user');
        $this->addSql('ALTER TABLE t_user DROP username, DROP password, DROP email, DROP is_active, CHANGE lg_USER_ID lg_USER_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_user_fone CHANGE lg_USER_FONE_ID lg_USER_FONE_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_USER_ID lg_USER_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_user_imprimante CHANGE lg_USER_IMPRIMQNTE_ID lg_USER_IMPRIMQNTE_ID VARCHAR(40) NOT NULL COLLATE utf8_general_ci, CHANGE lg_USER_ID lg_USER_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_IMPRIMANTE_ID lg_IMPRIMANTE_ID VARCHAR(40) NOT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE t_user_services CHANGE lg_USER_SERVICES_ID lg_USER_SERVICES_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_USER_ID lg_USER_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_warehouse CHANGE lg_WAREHOUSE_ID lg_WAREHOUSE_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_warehouse_contenance CHANGE lg_WAREHOUSE_CONTENANCE_ID lg_WAREHOUSE_CONTENANCE_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci, CHANGE lg_PRODUCT_ITEM_TYPE_CONTENANCE_ID lg_PRODUCT_ITEM_TYPE_CONTENANCE_ID VARCHAR(40) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_zonne_1 CHANGE lg_ZONNE_1_ID lg_ZONNE_1_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_zonne_2 CHANGE lg_ZONNE_2_ID lg_ZONNE_2_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_zonne_3 CHANGE lg_ZONNE_3_ID lg_ZONNE_3_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_zonne_4 CHANGE lg_ZONNE_4_ID lg_ZONNE_4_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_zonne_5 CHANGE lg_ZONNE_5_ID lg_ZONNE_5_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_zonne_6 CHANGE lg_ZONNE_6_ID lg_ZONNE_6_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE t_zonne_7 CHANGE lg_ZONNE_7_ID lg_ZONNE_7_ID VARCHAR(30) NOT NULL COLLATE latin1_swedish_ci');
    }
}
